import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import { ReduxProvider } from "@/redux/reduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen h-auto">
          <ReduxProvider>
            <Suspense>{children}</Suspense>
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}
